---
title: "Opening Ceremony"
format: html
---

## 

**Financing:**

Cantwell knows more about the background

The first directors of the newly formed company were; Chairman, Kennedy O’Brien, Managing Director; Reginald Dickens. The local interests were; Directors, Michael M Casey M.D. Patrick J Moloney Managing director of A. Moloney and Sons. **I will not bore the reader with the political endeavours and background negotiations that were played out as the foundations of the Industry were realised**. The Dungarvan Industrial development society of which Rev. T Walsh CC, BA was Chairman, were the sponsors.

**October, 9th 1935.**

**Eddie Cantwell's account:**

On the morning of October, 9th 1935.

At ten in the morning subscriptions opened for 12.000 preference, and 12.000 ordinary shares. One hour later they closed because of over subscription such was the interest. Keep in mind that blocks of shares were applied for by directors and their friends. Shares were also acquired by a number of business people in the town.

This was the first Company of its kind to be formed in the 26 Counties for the production of leather linings for the boot and shoe trade. The production of certain types of Chrome and vegetable leathers for boot uppers and sandals along with gloving and book binding leathers were also planned. Prior to this, Companies had to go abroad to find such items.

Most importantly, 100 men were to be employed once the company hit full production. Another interesting aspect of the newly formed Company was the sending of young men to the Technical School for training!

**Monday May 3, 1937**

The official opening took place on May.3rd 1937.It was indeed a big affair, Mr Lemass was met on the outskirts of the town by Rev. T.M Walsh, members of the Dungarvan Urban District Council, and the Civic guard formed a guard of Honour. The Minister was then marched into the square, led by Dungarvan brass band, and followed by a large crowd!

-   The town was decorated in flags and bunting, and

-   a large crowd followed the procession

-   to the Look-out where a make shift stage was erected.

-   On the stage the Minister was presented with an address of welcome from

    -    the urban council,

    -   the Dungarvan Industrial Development Association,

    -   the factory workers (of course),

    -    the Padraig Pearce Cumann, and

    -   the Cathal Brugha Cumann of Fianna fail.

    -   The Minister opened the factory with a golden Key!

    -   The factory was then blessed by the Bishop of Waterford and Lismore

    -   whilst the band played ‘Faith of our fathers!’

-   Later over toasts at a luncheon, the Minister was presented with a pair of slippers which were tanned at Dungarvan. Now there’s a nice little present to take home with you! I bet he was smiling quite openly when they gave him that! In

-   Factory had been in production for almost 12 months by now

-   All male labour, except for some clerical staff

-   120 operators, £300 weekly payroll

-   Old Dungarvan Technical School

-   Location:

    -   Dickens Leather CO. had to make extensive alterations to accommodate the premises to their purpose

-   Incorporated in October 1935

-   Of its nomimal capital of £40000, £24000 was issued

-   The sum asked for was oversubscribed

-   Dickens produced lining and upper leathers for boots shoes and slippers as well as leathers for gloving, clothing, belt braces, and fancy leather trades

------------------------------------------------------------------------

From The Dungarvan Leader

LEATHER FACTORY The End Of An Era! large adjoining premises running into Church Street, known locally as Barry's Corn Stores.

VIRTUAL MONOPOLY £24,000 was issued. The issue of shares was closed within a few minutes of the opening and the sum asked for was even oversubscribed.

culture,

Pictured at the official opening of the Dickens Leather Factory at the Look Out, Dungarvan in 1937 were (left to right) - James Dillon, T.D., Fine Gael, former Minister for Agri- Director of Dickens Leather Co., - Sean Lemass, Fianna Fail, Minister for Industry and Commerce, later to become Taoiseach, P. J. Little, T.D., F.F., Parliamentary Secretary, Joe Moloney, -, Dr. Michael Casey, Director of Dickens Leather Co., Jack Butler (partly hidden), Arthur Wright, leather sorter and BY AISLING CONROY This week to mark the closure of Dungar- van leather factory on the Quay after 60 years of operations, we recall the official opening of the plant back in 1937. In that year, the 'Cork Examiner' carried a full page feature on the new factory and gave a detailed account of the opening ceremony which was performed by Sean Lemass, Minister for Industry and Commerce, later to become Taoiseach.

#### **James Dillon**, 

T.D., Fine Gael, former Minister for Agri-

<https://seamusdubhghaill.com/2019/09/26/birth-of-james-dillon-fine-gael-leader/>

####  Sean Lemass, 

Fianna Fail, Minister for Industry and Commerce, later to become Taoiseach,

Joe Moloney,

Dr. Michael Casey, Director of Dickens Leather Co.,

Jack Butler (partly hidden),

Arthur Wright, leather sorter
