---
title: "background"
format: html
---

Questions

-   livestock trade from Ireland to Britain

    -   how many cows,

    -   which ferries,

-   Was Northern Ireland involved in the Economic War?

### **Background**

Economics of Southern Ireland

-   Punt is tied to sterling and thus massively overvalued

-   

**Cattle Ranching in Ireland**

-   Production line continued after independence, in fact the number of exported cattle grew into the 1950s

-   Ireland exported people, cattle and credit

-   Why no subsidiary industries

    -   ranchers had their connections in Britain

    -   credit in Ireland was really expensive

    -   lack of industry meant there was a lack of intra-class struggle between industrialists (who didn't exist) and bankers (who got to set the economic policy). CF Marx Das Kapital (where he explains much more detail about the internal nature of each class).

**Leather industry in Ireland**

-   After Independence, (?) much trade continued as before and Ireland exported huge numbers of live cattle to Britain, 'on the hoof', travelling on the ferries from Dublin (and Rosslare and the purpose-built port in Greenore, Co Louth?). This meant that there were no auxiliary trades (?) from animals, such as slaughtering, butchering and tanning the hides. Accordingly, the leather industry had completely vanished from Ireland and the leather sold in Ireland had to be imported back, tanned from hides of animals that had been reared here. While there may have been efficiencies arising from the larger scale of production in Britain, this was clearly an inefficient process and it starved Irish residents of employment – although not necessarily Irish people, as they often found work in Britain doing jobs that they could have been doing in Ireland.

Previously

-   Exporting beef & dairy, mostly to the UK, to feed the Brits (and the Irish working there – see my research on Greenore)

-   

## Economic War 1932-38

-   Tariffs, Self-determination, protectionist, self-sufficiency (nationalization, monopoly –\> ?precursors to fascism)
    -   world trade massively reduced (30%) between like 1929 and 1932, so it was going this way already, regardless of Dev
    -   Precipitated a need for new industry in ireland
        -   get list of industries
-   Economic War of 1932
    -   Economic was between Britain and Ireland (what about Norn Iron). It was triggered by the FF refusal to pay land annuities to the Brits so the Brits slapped a tariff onto agricultural imports, which was the bulk of the Irish economy (
    -   Ireland retaliated by putting a (?40%) tariff on imports from Britain
-   Blueshirts arise in response to
-   <https://irishhistoryshow.ie/109-the-economic-war/>
-   <https://www.youtube.com/watch?v=Gj4uVIpBwrw&list=PLxp9hs3yWXjNYN67Rw-Hncdo-_Us0rkCZ&index=5>
    -   *On this episode of the Irish History Show we discussed the Economic War, also known as the Anglo – Irish Trade War. It lasted from 1932 to 1938. When Fianna Fáil were first elected to government in 1932 they refused to continue paying the Land Annuities to the British government. This led to a series of retaliatory tariffs from both governments.

        The Fianna Fáil government used the dispute as an opportunity to build up domestic manufacturing behind these new tariffs. The economic war led to political instability and violence from sections of Irish society whose livelihoods were damaged by the trade war such as cattle graziers and exporters. It also led to the rise of the Blueshirts.*
-   Sean Lemass, miniser for Industry and commerce
-   New Industries in Ireland
    -   Motor Assembly (see bob Montgomery's book, commissioned by Frederick M SUmmerfield, anecdotes, history, family lore)
    -   

Wider background / Europe

-   protectionism in Europe

    -   story with Fascism and protectionism??

    -   "a bulwark against communism"

        -   The factory in Dungarvan:

-   Factory

    -   Why Dungarvan?

        -   close to the sea for effluent discharge

        -   proximity to hides

        -   tanning agents less of an issue

            -   Argentina, Mimosa (80% from South & East Africa) \[Press\]

                -   

    -   factory inputs

        -   Reginald Dickens for leather expertise

        -   Dr Michael M. Casey???

        -   Dungarvan Industrial Development Society

        -   Rev T Walsh

        -   Monsignor Richard Casey

    -   Capital

        -   crowdfunding - £1 per share, buncha locals + directors & friends, £24k total

        -   Irish Stock Exchange

        -   Dr Ann Casey???

    -   **Motivation**

        -   social stabilization

            -   Population decline in ireland versus industry presence

                -   Capital

                    -   Irish Stock Market 1930s

                    -   

                    -   

                    -   Q

                        -   Legacy:

                            -   multigeneration

-   

-   
