---
title: "Untitled"
format: html
---

The attendees at the opening ceremony provide us with an unusually succinct cross-section of society in the the fledgling Free State but, more interestingly, the composition points us to the different forces competing for what little bounty existed in what we would now think of as a Third World Country.

**Locals**

The great majority of attendees were of course locals and many of them would have their lives changed for the better in the coming decades, with regular work and good wages for the era, especially after they unionised in the 1940s. By the time the Opening Ceremony rolled around, the factory was already employing 120 people - mostly men, for reasons we shall come to. A large proportion of these would have been family men, breadwinners for their wives and frequently large families. It is hard to estimate how many people would be fed from the factory. Let's guess 70 breadwinners, each with a wife and a conservative average of three children (so far). That's 140 parents and 210 children, plus the other fifty workers not supporting a family, making 400 people to survive, plus plenty more unborn children as the workers would have been young and as fecund. The weekly wage bill was £300 for the entire workforce, money which would circulate around the town, with huge knock on effects for the local businesses and their families.

**Local v Urban split**

What's important is that the workers' money was to stay in the town but that the higher ups in the new company were split between local interests and parasitic city types whose role was to function as intermediaries between the town and the British - or indeed any other foreign - investment.

**Molony**

-   micro tycoon family

-   see house for example

    -   

**Austie Casey**

-   brilliant story of local doctor who managed to get his foot in the door of an industry

**Kennedy O'Brien**

Among the Directors was Kennedy O'Brien who brought *bona fide* native tanning experience. He grew up in Limerick working in O'Callaghan's Tannery, the last remaining large scale tannery on the island of Ireland. He moved to Dublin in 1927 and set up shop as a wholesale leather merchant. So when the industry began suddenly re-emerged in the 1930s, O'Brien was perfectly primed to get involved.

When Dickens Leather opened, he was already the managing director of the tannery in Portlaw which went by the homely-sounding *Irish Tanners Ltd.* In reality, as Daly notes, Irish Tanners was set up in collaboration with a British entrepreneur who owned *Western Tanning* of Bristol and Redvales, and this in turn was own by *Allied Leather*.

the various forces at play in the fledgling Irish Free State

-   great majority were just locals whose town would improve (wage bill)

-   pipe band and other celebrants

-   church

-   workers

-    directors

-   owner

-   politicians

Bigger Picture

-   world economics

-   protectionism

-   cattle export trade in ireland

Protectionism

-   jaskdfjlqk

-   Problems with protectionism

    -   Protectionism was a particularly good idea for the people from the small towns of Ireland who did not benefit directly from the livestock export trade, and their enthusiasm was expressed by their willingness to buy shares in protected industries. However, such good will and ambition was hardly sufficient for the practical realities of setting up new industries on the fly. It was not yet clear or fully understood whether these industries would lack economies of scale but there was a severe lack of Irish capital and local know-how in the many forms of manufacturing that were suddently required. Not only did Ireland have to teach its men how to fish, it also had to make the fishing rods and pay for them.

    -   

    -   Not only did the population have to learn how to

    -   The country lacked capital and know-whow

    -   James H Thomas had come close to hitting on the raw nerve of protectionism: the lack of Irish Capital, economies of scale and know-how.

**Lemass**

-   

-   The Directors of the company present an expression of the different forces and social groups inputting into the establishment of the factories.

    -    At the centre of it all was the Dublin-based government,

        -   represented by Sean Lemass, the new Minister of Industry (&&), who had the rather enormous task of delegating dozens of new factories to the towns and even villages of Ireland.

        -   One problem for Lemass was that he was a Dublin City man, born and bred, and too young to have had a chance to build the necessary network. So he hadn't yet developed the nationwide connections that his future son-in-law, Charlie Haughey, would later become renowned for. Thus Lemass needed needed people close to him who had to experience to negotiate the "ruddy-faced gombeenism of rural political patronage which was foreign to \[him\]".

        -   In his favour, however, Lemass had the twin hobbies of golf by day and poker by night, a game he became proficient in as a political prisoner in the Curragh during the Civil War. These hobbies gave him access to Dublin City's emerging new Catholic elites, while providing a human bridge of sorts between him and the local town councils that were clamouring for industry and cash.

**Vincent Crowley**

-   One such character was Vincent Crowley, an ambitious Dublin accountant whose company, Kennedy, Crowley & Co would eventually morph into today's KPMG. Crowley spent his early years in Cavan Town but had a mother from rural Cork, and he clearly knew how to negotiate the three main types of Irish community: Dublin City, rural Ireland and the towns of Ireland who were by now clamouring for the emerging new industries of the protection era.

    -   and his close business associate was the lawyer Arthur Cox.

        -   Crowley had his finger in a lot o pies and was involved in advising Lemass on where to locate his factories, while also benefiting from becoming the **accountant / auditor f**or the companies at the same time

            -   Crowley was also the Chairman of Irish Leathers Ltd who set up the factory in Portlaw with Kennedy O'Brien as Managingn Director, and an example of Crowley's ability to keep the locals happy was to have the first board meeting in Portlaw, rather than in Dublin where he and his set functioned as a financial intermediary between the foreign - i.e. British - capital and the factories scattered around Ireland (although notably on the Leinster side of the Shannon, as British companies had no interest in setting up disadvantageously far away).

            -   

            -   One reason for this was that the Department's predictions for the amount of leather needed within the state were grossly underestimated and Lemass later admitted that locating in Portlaw had been a mistake, even though it later grew into one of the biggest tanneries in all of Europe and, in the 1940s, a purpose-built factory would be put there. However, this overspill was to Dungarvan's advantage and O'Brien was on hand to straddle the two tanneries on opposing sides of the county. **WHY DID HE FLOG HALF OF HIS SHARES**

                -   O'Brien and the tannery empire of the south / east (New Ross, Carrick, Fethard, Gorey)

                -   This new urban milieu, who had spent the first decade of Free Statedom taking over from the old Unionist-sympathising elites, provided Lemass with the necessary bridge be

            -   

            -   Crowley worked in tandem with the lawyer Arthur Cox,

                -    whose Dublin-based firm had become a specialist in helping foreign companies – almost exclusively British companies which were familiar to Irish consumers – to set up shop in Ireland after the Trade War began, a practice known by the catchy moniker of tariff-jumping.

                -   The 1932 Control of Manufacturers Act set out specific criteria by which foreign investors could set up in a way that would suit the

                    -   LIST the conditions / priorities

                -   but Arthur Cox helped the British Investors to find ways around the rules.

                    -   For example, shareholdings had to be 51% Irish, but the wily Cox discovered that they could make a subdistinction between *voting* shareholders and *non-voting* shareholders, and thus the British Companies would maintain control over their new Irish branches.

                    -   Familiar brands doing this included Cadbury-Fry and Macintosh (CHECK DALY & PRESS), confectionists who were already dominant players in the Irish market, and still are to this day. The flow of factories was not exclusively in one direction and Guinness's set up their own factory in London during this period.

                    -   The footwear industry was particularly vulnerable to this kind of jiggery-pokery because the set up costs were relatively low compared to heavier industry.

                    -   As a result, the vast majority of employees in the tanning industry were in factories owned and, to some extent, run by British companies.

                -   

-   

-   

-   

**Lemass - Fianna Fail, Minister for Industry and Commerce, later to become Taoiseach,**

-   Background
    -   Capel St, fought in 1916 rising as a teenager
    -   quick bit of FF background (for him and its socialism) and why he was central too Dev.
    -   Jostling with MacEntee?
-   At every factory opening, Lemass looks like a polite but condescending French waiter (me)
-   p87 Bryce Evans
    -   a lot of well-connected people became rich - Garvin

    -   Lemass enjoiyed rounds of golf and poker schools with the men he perceived to be Ireland’s movers and shakers. He created openings both for people who moved in his circles and for other aspiring businessmen, particularly in clothing and footwear, industries which required relatively little initial capital.

    -    “the ruddy-faced gombeenism of rural political patronage was foreign to Lemass \[, who was\] a slick city type”

        Nonethe less at the very least it can be said that the system he set up in the 1930s facilitated patronage of this kind

    -   Location was not just determined by national and social needs; industries appeared in areas where Fianna Fail needed votes too

    -   

        -   Lemass let big British companies set up operations with a few Irish directors on thiem, aware that the real decisions were made at the company’s headquarters in Britain. (Cadbury’s & Fry, Dunlop, etc)

        -   

        -   His anglocentrism aside, James H Thomas had come close to hitting on the raw nerve of protectionism: the lack of Irish Capital, economies of scale and know-how.

            -   

            -   “lack of technical expertise in the country”

            -   

            -   foreign firms manipulated shareholding patterns to get around the restrictions of the control of manufacturers act

            -   

            -   “the policy of native control of industry was in practice diluted”

            -   

        -   
-   Crowley
    -   In 1932 his partnership with Kennedy ended acrimoniously. After buying Kennedy out in June, he continued as principal of Kennedy, Crowley and Co., operating from 4/5 Westmoreland Street.
        -   <https://www.dib.ie/biography/crowley-vincent-a9610#:~:text=Crowley%2C%20Vincent%20(1890%E2%80%931965,Armagh.>
        -   Irish Life Assurance Company –\> did audits for them and it was they who bought out Joan Casey
        -   Crowley's relationship with Lemass enabled his firm to benefit from Fianna Fáil's more interventionist approach, and he picked up audits and consultancy work with semi-state entities such as Aer Lingus and the Irish Life Assurance Company, and with newly established industrial companies operating under close state supervision, including the Irish Aluminium Company, the Irish Sugar Company, Irish Wire Products Ltd, Irish Ropes Ltd, Salts (Ireland) Ltd, Irish Worsted Mills Ltd and Cement Ltd. He played a pivotal role in providing administrative support for a late-emerging industrial sector. As well as advising and seconding employees to these new companies, he served for many years as chairman of Irish Tanners Ltd.
        -   Kennedy, Crowley's industrial clients were mainly Irish subsidiaries of foreign concerns, and the Control of Manufactures Acts of 1932 and 1934 required new manufacturing companies to be 51 per cent Irish-owned, subjecting those not meeting this criterion to a restrictive and cumbersome licencing system. Operating in tandem with Cox, Crowley helped his clients to evade these legislative entanglements. Aware that it needed foreign investment and technical expertise for its industrialisation drive, the government tacitly encouraged their activities, making only token efforts to close off loopholes in the law.
        -   iall served as chairman of AIB and the Irish Life Assurance Company,

p82

Joe McGrath: donated a whopping £500

-   initially rejected but Lemass sanctioned it
-   this was the beginning of the rot in Fianna Fail, according to Gerard Boland’s son, kevin

Lemass’s lack of Ethics
