---
title: "trip1"
format: html
---

## 

**Sure enough, it’s nice and bright on my arrival in Dungarvan, which sits like a miniature Dublin, inside into a protected bay, a river splitting it in two even-ish parts, and hills to its admittedly north, although it’ll be a few decades before they have to fend off the sprawl**

**Dungarvan geography**

I like to think of Dungarvan as a miniature version of Dublin. The town sits at the centre of a delightful, semi-circular bay, a river splits it in two, and the Comeragh Mountains sit behind, albeit to the north.

**because the settlement is on the south coast and everything is rotated 90 degress compared to the East-facing capital city.** The more prosperous side is to the west – that's Dungarvan proper – while Abbeyside is to the east of the river.

I'm coming from Waterford City so I get some free parking in Abbeyside and take my needlessly bike with me to the

with Dungarvan town being on one side

I like to think of Dungarvan as a miniature version model of Dublin as it sits at the centre of a delightful, semi-circular bay

is split by a river which flows into a large bay

with the town being at the centre of a large C-shaped bay, split in the middle

-   park on Abbeyside as it's free

    -   bring my bike

    -   map of surrounding area with bike trails

        -   comeragh as wicklow mountains. 170k Sean Kelly Challenge

-   left along docks, haven't been here before

-   library is there, supervalu in an old stone building, done up a little

-   the tannery is not quite on a the docks but inland one block

    -   old famine building. restaurant inside plus another closed down jobbie.

    -   place is rammed with fancy looking restaurants and zero footfall. must be for tourists. this is the dungarvan's temple bar but a bit fancier

    -   Essentially it's a micro peninsula with no purpose in the modern world other than being a nice place for tourists to visit or locals to live, and the town hasn't really shifted down this way.

    -   Dungarvan is a shallow water harbour (and the tide is out this morning) so the docks have been closed down and there are no ships loading or unloading goods (freight?)

    -   

-   I head to the library. I'm due to meet Will Fraher but he's not here. I chat to the librarian, a ratty-faced bearded chap out vaping. libro isn't open yet but theres' groups and whatnot coming on

    -   he tells me Will was there yesterday and i'm gutted. I've driven all the way here to see him and find out about the town and now he's stood me up

        -   says the country archivist will be back after 2 so come then.

    -   i get to the county museum

        -   big divide between country and city

            -   it was the first thing The Big Man said to me and it immediately made sense cos there's a mountain range splitting the county down the middle and a big dollop of nothing between it and the city slash Tramore slash Dunmore & Passage East

        -   show map of the county, possibly with lights, or mountains or relief etc.

    **Waterford County Museum**

    -   I tell the lady I was supposed to meet Will Fraher in the libro but he stood me up and then suddenly he appears and everyone is scarlet and it's an awful start. I must've mixed up the county archives in the library with the archives in the county museum

-   Fraher preps the materials for me. They are kept in a numbered box up or downstairs and he comes back and, along with a colleague, they take ages getting the scrap book in place. I hadn't quite understood what I was here for but he knew. He tells me that the Monsignor Casey had kept every newspaper scrapping, and he has a dirty smile on his face, and I\@m thinking he's thinkng the Monsignor was a big fan of himself.

-   The scrap book is enormous. Like a book of Kells jobbie and the binding isn't strong enough to hold together. There are several hundred pages of high quality paper, for which the binding was made, but every bit of each side of every page is overlaid with glue and newspaper clippings

    -   At first

-   I immediately recognise bits of scrappings and photos that William Fitzgerald has taken pictures of. Luckily I've managed to see these already because he sent me the photos he took on his iPhone and I downloaded an app called nomacs to help me view the poxy ass HEIC files he took.

-   The scrapbook begins with clippings related to the family which may have been added afterwards and afterwards it follows something of a chronological format

    -   Time in New York

    -   Military Chaplain

    -   Skerries PP

        -   loadsa dead priests

    -   Other scrapbook

I'm

Walk around town centre

-   a car park in the square. atmos is ruined by it

-   all slightly depressing

-   grey, not much happening

------------------------------------------------------------------------

I think the lads might also be secretly worried about the lack of material too. William has just emailed some relatives of his – all descendants of Michael J – and he said the following:

*We think there's a compelling story here about early Irish industrialists, and their links to both the church and politics of the day.* 

The fear of course is that there isn't a compelling story. But it's good to hear him summarise the project in one sentence.

Richard Fitz

-   years of fighting about the trust, the lads don't reallly know how the O'Shea's got involved and they

-   like really petty Irish stuff, not big stuff

-   but because our mum was the fourth and the baby, nad our dad did

-   we don't want to do a book on the trust and

-   there's that lady

Willima

-   i don't htink

-   Richard was in charge of all they wills but an Pierce died also around the same time but all the wills went to the sister - May O'Shea - her son Michael O'Shea, she gets involved in the 50s & 60s

-   basically lots of fights among the cousins. "It's not that interesting

-   
